global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push
    basic_auth:
      username: "${GRAFANA_API_USER}"
      password: "${GRAFANA_API_KEY}"

scrape_configs:
  - job_name: 'ecs-nginx-exporter'
    static_configs:
      - targets: ['10.10.101.76:9113']

  - job_name: 'ecs-app'
    static_configs:
      - targets: ['10.10.102.79:5000']
